[project]
name = "pynvr"
version = "1.0.0"
description = "pynvr is a NVR used to record events from cameras"
authors = [{ name = "Gordon Aspin", email = "gordon.aspin@gmail.com" }]
dependencies = [
    "click==8.4.1",
    "opencv-contrib-python-headless==4.13.0.92",
    "scikit-image==0.26.0",
    "ultralytics==8.4.66",
    "ultralytics-thop==2.0.20",
    "aiortc==1.14.0",
    "fastapi==0.136.3",
    "bcrypt==4.3.0",
    "passlib==1.7.4",
    "uvicorn==0.49.0",
    "keyring==25.7.0",
]
requires-python = "==3.12.13"
readme = "README.md"
license = "MIT"
maintainers = [{ name = "Gordon Aspin", email="gordon.aspin@gmail.com" }]
classifiers=[
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
]
[project.scripts]
pynvr = "backend.app:main"

[project.urls]
Repository = "https://github.com/gordonaspin/pynvr"

[tool.pylint]
# Disable specific messages by their symbolic name or ID.
disable = [
    "import-error",
    "no-member",
    "too-many-instance-attributes",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-locals",
    "no-value-for-parameter",
    "too-few-public-methods",
    "broad-exception-caught",
]
[tool.setuptools]

[tool.setuptools.packages.find]
exclude = ["logs*", "recordings*", "frontend*"]
